#pattern1
print(1)
print(2,end=' ')
print(3)
print(4,end=' ')
print(5,end=' ')
print(6)
print()
#pattern2
print('1&')
print(2,end='*')
print(3,end='&\n')
print(4,end='*')
print(5,end='*')
print(6,end='&')